args:
  task_name: long_term_forecast
  is_training: 1
  model_id: optuna_tune
  model: DLinear
  data: custom
  root_path: /home/hung-tran-nam/SWAT_AI-LOOV/dataset
  data_path: VIC.csv
  target: Low,High
  features: MS
  freq: m
  num_kernels: 6
  checkpoints: ./checkpoints/
  loss: MSE
  des: optuna
  train_epochs: 100
  itr: 1
  use_amp: false
  num_workers: 5
  seg_len: 24
  bidirectional: true
  kfold: 0
  pred_len: 12
  moving_avg: 3
  distil: true
  use_norm: 1
  use_gpu: false
  gpu: 0
  gpu_type: cuda
  use_multi_gpu: false
  devices: 0,1,2,3
  use_dtw: true
  seasonal_patterns: Monthly
  embed: timeF
  seed: 42
  seq_label_len: !!python/tuple
  - 36
  - 36
  dropout: 0.21186023134240262
  lradj: type3
  learning_rate: 0.0006321732490144021
  activation: relu
  batch_size: 8
  d_model: 8
  n_heads: 1
  e_layers: 6
  d_layers: 1
  d_ff: 32
  factor: 3
  seq_len: 36
  label_len: 36
  enc_in: 2
  dec_in: 2
  c_out: 2
  patience: 3
  inverse: true
  device: !!python/object/apply:torch.device
  - cpu
