args:
  task_name: long_term_forecast
  is_training: 1
  model_id: optuna_tune
  model: DLinear
  data: custom
  root_path: /home/hung-tran-nam/interval-valued-TS/dataset
  data_path: T.csv
  target: Low,High
  features: MS
  freq: m
  num_kernels: 6
  checkpoints: ./checkpoints/
  loss: MSE
  des: optuna
  train_epochs: 100
  itr: 1
  use_amp: false
  num_workers: 5
  seg_len: 24
  bidirectional: true
  kfold: 0
  pred_len: 12
  moving_avg: 3
  distil: true
  use_norm: 1
  use_gpu: false
  gpu: 0
  gpu_type: cuda
  use_multi_gpu: false
  devices: 0,1,2,3
  use_dtw: true
  seasonal_patterns: Monthly
  embed: timeF
  seed: 42
  seq_label_len: !!python/tuple
  - 72
  - 12
  dropout: 0.1260937511394287
  lradj: type3
  learning_rate: 4.913620932233383e-05
  activation: silu
  batch_size: 4
  d_model: 32
  n_heads: 4
  e_layers: 4
  d_layers: 5
  d_ff: 8
  factor: 1
  seq_len: 72
  label_len: 12
  enc_in: 2
  dec_in: 2
  c_out: 2
  patience: 3
  inverse: true
  device: !!python/object/apply:torch.device
  - cpu
