args:
  task_name: long_term_forecast
  is_training: 1
  model_id: optuna_tune
  model: DLinear
  data: custom
  root_path: /home/hung-tran-nam/interval-valued-TS/dataset
  data_path: Temp.csv
  target: Low,High
  features: MS
  freq: w
  num_kernels: 6
  checkpoints: ./checkpoints/
  loss: MSE
  des: optuna
  train_epochs: 100
  itr: 1
  use_amp: false
  num_workers: 5
  seg_len: 24
  bidirectional: true
  kfold: 0
  pred_len: 52
  moving_avg: 3
  distil: true
  use_norm: 1
  use_gpu: false
  gpu: 0
  gpu_type: cuda
  use_multi_gpu: false
  devices: 0,1,2,3
  use_dtw: true
  seasonal_patterns: Monthly
  embed: timeF
  seed: 42
  seq_label_len: !!python/tuple
  - 224
  - 32
  dropout: 0.010223050453432234
  lradj: type1
  learning_rate: 0.00014182636704133773
  activation: silu
  batch_size: 8
  d_model: 32
  n_heads: 4
  e_layers: 1
  d_layers: 6
  d_ff: 64
  factor: 3
  seq_len: 224
  label_len: 32
  enc_in: 2
  dec_in: 2
  c_out: 2
  patience: 3
  inverse: true
  device: !!python/object/apply:torch.device
  - cpu
